baseurl: /
title: Ian McDonald
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author:
  avatar: img/avatar.png
  bio: Ian has done a lot of stuff
  name: Ian McDonald
Params:
  authorbox: yes
  description: Ian McDonald's all purpose website
  logo:
    subtitle: Politics and movies, movies and politics
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  style:
    vars: "#1d5f94"
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
